apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-gitea

commonLabels:
  app: gitea

resources:
  - deployments/gitea.yaml
  - deployments/mysql.yaml
  - deployments/sshServer.yaml
  - resources/namespace.yaml
  - resources/service.yaml
  - resources/ingress.yaml
