apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  namespace: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  replicas: 1 # tells deployment to run 2 pods matching the template  
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: jenkins
        image: gitea/gitea:1.15.4
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 22
          name: gitea-ssh
          protocol: TCP
