apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-server
  namespace: gitea
spec:
  selector:
    matchLabels:
      app: ssh-server
  replicas: 1
  template:
    metadata:
      labels:
        app: ssh-server
    spec:
      containers:
      - name: ssh-server
        image: linuxserver/openssh-server
        imagePullPolicy: Always
        ports:
          - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-server
  namespace: gitea
spec:
  type: NodePort
  selector:
    app: ssh-server
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
    name: ssh