apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-nginx

commonLabels:
  app: nginx

resources:
  - deployments/ngnix.yaml
  - resources/namespace.yaml
  - resources/service.yaml