apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - nodePort: 30080
      port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx