apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-jenkins

commonLabels:
  app: jenkins

resources:
  - deployments/jenkins.yaml
  - resources/namespace.yaml
  - resources/service.yaml
  - resources/ingress.yaml


configMapGenerator:
  - name: jenkins-plugins-cm
    behavior: create
    namespace: jenkins
    files: 
      - jenkins-plugins.txt